# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 山暮云秋的空间
subtitle: "千里关山边草暮，一星烽火朔云秋。"
description: "知识分享与生活记录"
keywords:
  - 山暮云秋
  - Blog
  - 博客
  - 山暮云秋的空间
  - 编程知识
  - 教程
  - blog.muyun.space
author: 山暮云秋
language: zh-CN
timezone: "Asia/Shanghai"

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://blog.muyun.space
# 已被注释
# permalink: :year/:month/:day/:title/
# permalink_defaults:
root: /
permalink: posts/:abbrlink/
abbrlink:
  alg: crc32 # support crc16(default) and crc32
  rep: hex # support dec(default) and hex
  drafts: false # (true)Process draft,(false)Do not process draft
  # Generate categories from directory-tree
  # depth: the max_depth of directory-tree you want to generate, should > 0
  auto_category:
    enable: false # 默认为 true， 手改改为 false
    depth:

pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md
  - baidu_verify_codeva-NfyAifG02r.html
  - vercel.json
  - api/proxy.js

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: false
  tab_replace: ""

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 8
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: yun

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment

# deploy:
# type: git
# repo: https://github.com/ShanMuYunQiu/MuYun_Blog
# branch: master
# message: 更新Hexo博客内容

live2d:
  enable: true
  # 推荐使用 jsdelivr 的 CDN 来加载
  scriptFrom: https://cdn.jsdelivr.net/npm/live2d-widget@3.x/lib/L2Dwidget.min.js
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    # 推荐使用 CDN 来加载模型
    use: https://cdn.jsdelivr.net/npm/live2d-widget-model-wanko@latest/assets/wanko.model.json
  display:
    superSample: 2
    width: 200
    height: 400
    position: right
    hOffset: 0
    vOffset: -100
  mobile:
    show: false
  dialog:
    # 是否开启对话框
    enable: false
    # 是否使用一言
    hitokoto: false

# Security
encrypt: # hexo-blog-encrypt
  abstract: ヾ(✿ﾟ▽ﾟ)ノ这篇文章被加密了！输入密码才能查看哦！
  message: ヾ(๑╹◡╹)ﾉ"文章被加密，点击这里输入密码查看~~~
  tags:
    - { name: 私密, password: qwertyuipo1130 }
    - { name: tagName, password: 密码B }
  theme: wave
  wrong_pass_message: 密码错误哦！如果不知道密码就不要试了！别想偷看！￣へ￣
  wrong_hash_message: sorry，出现了未知的错误，但您还是可以查看文章内容[・_・?]

# hexo-github-canlendar
# 贡献度热力图插件 https://github.com/Barry-Flynn/hexo-github-calendar
githubcalendar:
  enable: true # 是否启用本插件
  enable_page: / # 要生效的页面，如 / 首页，/about/ 介绍页等
  user: ShanMuYunQiu # GitHub 用户名
  layout:
    type: id
    name: recent-posts
    index: 0
  githubcalendar_html: '<head><style type="text/css">@media (max-width: 1000px){.recent-post-item{width:95% !important;}}@media (min-width: 1000px){.recent-post-item{max-width:940px;width:100%;margin:0 auto;}}@media (max-width: 480px){.recent-post-item{padding:10px;}}</style></head><div class="recent-post-item" style="width:100%;height:auto;padding:20px;"><div id="github_loading" style="text-align:center;"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50" style="width:50px;height:50px;margin:0 auto;"><path fill="#d0d0d0" d="M25.251,6.461c-10.318,0-18.683,8.365-18.683,18.683h4.068c0-8.071,6.543-14.615,14.615-14.615V6.461z" transform="rotate(275.098 25 25)"><animateTransform attributeType="xml" attributeName="transform" type="rotate" from="0 25 25" to="360 25 25" dur="0.6s" repeatCount="indefinite"></animateTransform></path></svg></div><div id="github_container"></div></div>'
  pc_minheight: 280px
  mobile_minheight: 0px
  # 贡献统计的梯度色卡值，可自行调整
  color: "['#ebedf0', '#ffd1b3', '#ffb380', '#ffa366', '#ff9c59', '#ff944d', '#ff8c40', '	#ff8533', '#ff7d26', '#ff7519', '#ff6600']"
  # 推荐填写你自建的API接口，方法详见本插件配套Python后端 https://github.com/Barry-Flynn/python_github_calendar_api
  api: https://github-calendar-api.meta-code.top/api
  # 推荐下载后使用本地文件
  # calendar_js: https://cdn.jsdelivr.net/gh/barry-flynn/hexo-github-calendar/hexo_githubcalendar.js # 在线文件，容易加载失败
  calendar_js: https://cdn.jsdelivr.net/gh/barry-flynn/hexo-github-calendar/hexo_githubcalendar.js # 本地文件，请下载到主题文件夹的source目录下
  plus_style: ""

aplayer:
  cdn: https:///cdn.jsdelivr.net/npm/aplayer@latest/dist/APlayer.min.js
  style_cdn: https:///cdn.jsdelivr.net/npm/aplayer@latest/dist/APlayer.min.css
  meting: true
  meting_cdn: https:///cdn.jsdelivr.net/npm/meting@1/dist/Meting.min.js

sitemap:
  path:
    - sitemap.xml
    - sitemap.txt
  template:
  template_txt:
  rel: true
  tags: true
  categories: true

hexo_submit_urls_to_search_engine:
  submit_condition: count # 链接被提交的条件，可选值：count / period，现仅支持 count。
  count: 100 # 提交最新的 100 个链接。
  period: 100000 # 提交修改时间在 100000 秒内的链接。
  google: 0 # 是否向 Google 提交，可选值：1 / 0（0：否；1：是）
  bing: 1 # 是否向 Bing 提交，可选值：1 / 0（0：否；1：是）
  baidu: 1 # 是否向 Baidu 提交，可选值：1 / 0（0：否；1：是）
  txt_path: submit_urls.txt
  baidu_host: https://blog.muyun.space
  baidu_token: A6dZMEMdwydPianF
  bing_host: https://blog.muyun.space
  bing_token: c7114aa03dab43a696e023e65ba5b402
  google_host: https://jinghu-moon.top ## 在谷歌站长平台注册的域名。
  google_key_file: central-droplet-337107-098e588b1d98.json #存放google key 的 json 文件，与hexo _config.yml文件放于同一路径。不要把json 文件直接发布在公众仓库里!
  google_proxy: http://127.0.0.1:7890 # 向谷歌提交网址所使用的系统http 代理，填 0 不使用。以 Clash for Windows 为例。必须使用代理，否则，本地谷歌推送会失败
  replace: 0 # 是否替换链接中的部分字符串，可选值：1 | 0（0：否；1：是）
  find_what:
  replace_with:

deploy:
  - type: cjh_google_url_submitter
  - type: cjh_bing_url_submitter
  - type: cjh_baidu_url_submitter
